### PR TITLE
backport frontend changes to v5

### PR DESCRIPTION
**Pull request by johnduffell**
this should go in as 5.0.8 for frontend

it's changes in https://github.com/guardian/frontend/pull/12338
as well as previous changes in https://github.com/guardian/frontend/pull/11961

I will merge this to the 5.0.master maintenance branch I just created, and then tag it so we can pull into frontend in future.

@OliverJAsh :determined: :elephant:

### CODE REVIEW

**Comment by OliverJAsh** [comment]
Before we bump, does the existing 5.0.7 play nicely in frontend?

**Comment by johnduffell** [comment]
the existing 5.0.7 is missing the two things I've backported from that file, however I forgot to check any other files for missing changes.  I'll do that too!

**Comment by johnduffell** [comment]
@OliverJAsh yes looks like everything else is the same that needs to be:
```
$ diff -r pasteup-forms frontend/static/src/stylesheets/components/pasteup-forms
Only in frontend/static/src/stylesheets/components/pasteup-forms: .bower.json
Only in pasteup-forms: .git
Only in pasteup-forms: build
```

**Comment by rich-nguyen** [comment]
:+1:

**Pull request merged**
